### ISSUE TITLE
[QA] First login of admin user fails using HTTPS://

### ISSUE THREAD

**Issue by jnweiger** [owncloud/qnap#23]
Seen with owncloud for QNAP 10.8.0 RC1 from `ownCloud_10.8.0_arm-x41.qpkg` using Firefox 89.0.2

* with a fresh browser session (no cookies) visit https://10.90.4.178/owncloud
* Enter credentials for user admin.
* The browser redirects to https://10.90.4.178/owncloud/apps/files, but violates the HTTP protocol:
  The Request has `undefined` in the GET command.
```
GET /owncloud/apps/files/ undefined
Host: 10.90.4.178
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Cookie: ocrpqgcia1h2=ik1r7rlkn1jjvbu05e7e9cp9nt; oc_sessionPassphrase=GsCkj5FBLoPUhXqtFKHjVM8Ys%2BYwXXoIhQP659jK1n7S%2BdoKxK6OI2UEbUk2n3%2FihfErb1oKoDoCmx2sVPu3b0jDnWGta%2BZNsC0xI%2FCZbjf1dbx7tiYqJiSCJya7flWo
Upgrade-Insecure-Requests: 1
```

With a shift reload, the request turns into `GET /owncloud/apps/files/ HTTP/1.1` and succeeds.

Using http://10.90.4.178:8080/owncloud for the initial login works immeditely

**Comment by jnweiger** [comment]
With google-chrome and https, the login page already fails to load. Cannot test that redirect.
Using http://10.90.4.178:8080/owncloud also works with google-chrome.

**Comment by jnweiger** [comment]
This is with a qnap machine from factory reset. It probably has no valid ssl certificate ...

**Comment by wkloucek** [comment]
caused by https://github.com/owncloud/qnap/issues/40
