### ISSUE TITLE
[QA] QNAP App Container Station does not show a running ownCloud container

### ISSUE THREAD

**Issue by jnweiger** [owncloud/qnap#24]
Seen with owncloud 10.8.0 for QNAP

* Install ownCloud -> verify it is running, by logging in admin user.
* Visit App Center -> Container Station
* the running ownCloud container is not visible in the Container Station dialog.
![image](https://user-images.githubusercontent.com/1108546/126996407-a030b891-38be-41e0-87aa-cdf3ab43136b.png)

Expected behaviour: ownCloud can be seen there, (or remove the Container Station dependency from ownCloud)

**Comment by wkloucek** [comment]
That is expected and wanted. ownCloud is run as a system app and therefore not shown in there so that the user can not mess with it. On the CLI it will also not show up if you do a simple `docker ps`. You run `system-docker ps` you will also see the ownCloud stuff.
