### ISSUE TITLE
[QA] qpkg package of RC1 should have RC1 in its name

### ISSUE THREAD

**Issue by jnweiger** [owncloud/qnap#26]
Seen with owncloud for QNAP 10.8.0 RC1

The package is currently named `ownCloud_10.8.0_arm-x41.qpkg`

Expected behaviour: Pre-release version (beta, RC) are clearly marked as such.

**Comment by jnweiger** [comment]
The version of the owncloud/qnap app should be also visible in the ownCloud_10.8.0_*.qpkg package names. (E.g. as ownCloud10.8.0_qnap1.4.0_arm.qpkg)

See also #32

**Comment by wkloucek** [comment]
we decided to add a counter to the ownCloud (Core) version, which reflects different builds of the QPKG.
This will increase whenever a non Core dependency is updated.

See also https://github.com/owncloud/qnap-packaging/releases
