### ISSUE TITLE
App not signed. 

### ISSUE THREAD

**Issue by JKawohl** [owncloud/qnap#3]
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- qnap
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\MissingSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [qnap] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\MissingSignatureException
                    [message] => Signature data not found.
                )

        )

)

Taken from https://github.com/owncloud-docker/qnap

**Comment by JKawohl** [comment]
fine for now but needs signing when final release

**Comment by DeepDiver1975** [comment]
this is standard release process - no need to have a ticket open
