### ISSUE TITLE
Guests app does not work due to incorrect forwarding

### ISSUE THREAD

**Issue by GeraldLeikam** [owncloud/qnap#30]
After creating a share for a guest user, he or she will receive the email and can also call up the link for setting the password, but the automatic forwarding (after clicking on "Set Password") does not work because it is apparently redirected from https to http. 

I suspect the password is not saved in the database because the previously set password does not work after calling the login link.

**Comment by jnweiger** [comment]
The owncloud app in my qnap test instance presents itself on https:/10.90.4.178/owncloud and on http:/10.90.4.178:8080/owncloud
The link in the invitation mail is incorrect. It should either have https:// or the :8080 port number:

![image](https://user-images.githubusercontent.com/1108546/127160296-a42fb592-db93-4e31-9161-254d35cf6b76.png)

**Comment by jnweiger** [comment]
Re-testing with with ownCloud for QNAP 10.8.0 from `ownCloud_10.8.0_arm-x41.qpkg` (dated 2021-07-27)

**Comment by wkloucek** [comment]
caused by https://github.com/owncloud/qnap/issues/40

**Comment by jnweiger** [comment]
Retested with  https://github.com/owncloud/qnap-packaging/releases/tag/v10.8.0.0-rc3

* admin user is logged in via https://10.90.4.174/owncloud and creates the guest share: link works. :heavy_check_mark: 
* admin user is logged in via http://10.90.4.178:8080/owncloud and creates the guest share: link works. :heavy_check_mark:

Confirmed fixed.
