### ISSUE TITLE
[QA] version number of the owncloud/qnap app mismatches

### ISSUE THREAD

**Issue by jnweiger** [owncloud/qnap#32]
Seen with ownCloud for QNAP 10.8.0 RC1 from ownCloud_10.8.0_arm-x41.qpkg (dated 2021-07-19)

Github release has v1.4.0
![image](https://user-images.githubusercontent.com/1108546/127163504-074f167b-e1f8-401a-a44c-126c94c50391.png)

----

The installed system has 0.2.0
![image](https://user-images.githubusercontent.com/1108546/127163543-03f7b068-5d63-4bb5-a6a9-fc7c27f08042.png)

This makes it diffcult to say, if a current version is actually installed. Thus all bug reports relating to this app may be considered invalid.

Expected behaviour: 
* The version numbers match, and get incremented after every update.
* The version of this app should be also visible in the ownCloud_10.8.0_*.qpkg package names. (E.g. as `ownCloud10.8.0_q1.4.0_arm.qpkg`)

**Comment by wkloucek** [comment]
new RC fulfills that https://github.com/owncloud/qnap-packaging/releases/tag/v10.8.0.0-rc3
