### ISSUE TITLE
running occ commands does not work as documented

### ISSUE THREAD

**Issue by workflowsguy** [owncloud/qnap#46]
I need to run an update through occ

According to the [documentation](https://doc.owncloud.com/server/10.9/admin_manual/qnap/#running-occ-commands), this should work with

`docker exec --user www-data <owncloud-container-name> php occ <your-command>`

Output of `system-docker ps` gives:
```
CONTAINER ID   IMAGE                        COMMAND                  CREATED        STATUS                  PORTS                       NAMES
95341d768bdb   owncloud/qnap:10.8.0-amd64   "/usr/bin/entrypoint…"   45 hours ago   Up 45 hours (healthy)   127.0.0.1:11409->8080/tcp   owncloud_owncloud_1
7d9eb37ae8c4   redis:6.2.5-alpine           "docker-entrypoint.s…"   45 hours ago   Up 45 hours             6379/tcp                    owncloud_redis_1
1a0e8f158e7d   postgres:13.4-alpine         "docker-entrypoint.s…"   45 hours ago   Up 45 hours             5432/tcp                    owncloud_db_1
```

But when I run

`docker exec --user www-data owncloud_owncloud_1 php occ`,

 I get

`Error: No such container: owncloud_owncloud_1`

**Comment by wkloucek** [comment]
true, this is wrong. `system-docker exec --user www-data owncloud_owncloud_1 occ` should do the trick.

I'll take care about updating the docs.

**Comment by wkloucek** [comment]
An even better solution is to navigate to `/share/CACHEDEV1_DATA/.qpkg/ownCloud` and then run `system-docker-compose exec --user www-data owncloud occ`
